# Generated by Django 5.0.2 on 2024-02-08 02:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('PHONE', 'Phone'), ('TABLET', 'Tablet'), ('LAPTOP', 'Laptop')], max_length=200)),
                ('model_no', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DelegateTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(default=datetime.datetime.now)),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('assets', models.ManyToManyField(blank=True, related_name='asset', to='track.asset')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegateto', to='track.employee')),
            ],
        ),
        migrations.CreateModel(
            name='GiveBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_condition', models.CharField(max_length=200)),
                ('returned_date', models.DateTimeField(default=datetime.datetime.now)),
                ('delegat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_name', to='track.delegateto')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_model', to='track.asset')),
            ],
        ),
    ]
